# Generated by Django 6.0.3 on 2026-03-31 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_rastreio', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('CO', 'Coletado'), ('SE', 'Em Secagem'), ('MO', 'Em Moagem'), ('AN', 'Em Análise'), ('FI', 'Finalizado'), ('DE', 'Descartado')], default='CO', max_length=2)),
                ('localizacao_bancada', models.CharField(blank=True, help_text='Ex: Estufa 02, Prateleira C', max_length=150)),
                ('data_coleta', models.DateTimeField()),
                ('data_limite_analise', models.DateTimeField(help_text='Tempo de retenção máximo antes da análise química')),
                ('ponto_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amostras', to='areas.pontosondagem')),
            ],
        ),
    ]
