# Generated by Django 6.0.3 on 2026-03-31 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amostras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoLaboratorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Fósforo (P)')),
                ('k', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Potássio (K)')),
                ('ca', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Cálcio (Ca)')),
                ('mg', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Magnésio (Mg)')),
                ('h_al', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Acidez Potencial (H+Al)')),
                ('argila', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Argila (%)')),
                ('silte', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Silte (%)')),
                ('areia', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Areia (%)')),
                ('data_laudo', models.DateTimeField(auto_now_add=True)),
                ('fechado', models.BooleanField(default=False, help_text='Se True, bloqueia edições para garantir auditoria.')),
                ('amostra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='amostras.amostra')),
            ],
        ),
    ]
