# Generated by Django 6.0.3 on 2026-03-31 14:57

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('municipio', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Talhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_talhao', models.CharField(help_text='Ex: Gleba A, Talhão 01', max_length=50)),
                ('area_hectares', models.DecimalField(decimal_places=2, max_digits=8)),
                ('historico_manejo', models.TextField(blank=True, help_text='Registro de intervenções anteriores (calagem, adubação, etc.)')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talhoes', to='areas.fazenda')),
            ],
        ),
        migrations.CreateModel(
            name='PontoSondagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='Ex: Ponto 01', max_length=50)),
                ('coordenadas', django.contrib.gis.db.models.fields.PointField(help_text='Coordenadas geográficas da extração', srid=4326)),
                ('data_marcacao', models.DateTimeField(auto_now_add=True)),
                ('talhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos', to='areas.talhao')),
            ],
        ),
    ]
