# Generated by Django 6.0.3 on 2026-04-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosondagem',
            name='tipo_matriz',
            field=models.CharField(choices=[('SO', 'Solo (Agronômica/Pedologia)'), ('AG', 'Água (Hidrologia/Qualidade)')], default='SO', max_length=2, verbose_name='Tipo de Matriz Coletada'),
        ),
    ]
